### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-indieauth#18]
Got this on https://datasette-indieauth-demo.datasette.io/-/indieauth/done?code=N4t1BH3NL_mJTE3PKpZJ4A%3D%3D.-dL4zf8DNpRa0OQHvtdIYImxaPRGwQGjs8l-7thgfeXnDyOYCm0ms03kD6FZzCSCSiGhCGrVNRyiP_m3s0IWbLdTHHSGiYG0ivRwtnnN4NccPOikjKs8dC1gIukZQDtMETWo293_t_V3plLPFh0borO0eOMI64NLqBt9zc9fHmtu6suStEaiTDeom0OF0vtw1JjdK8tptEHc0EDirvQzLQBJX2oPP0D730GYtHnMtrHiEyEU2WzX0ikl-Bae9XYAjUeQTyyO227UJVro19Db6RCJTpyQxizkvP5y4kd9OBxiHFmObqNuuFv6-__C9BGJr3Ie5UC4OstQU0tyS9Mbz-OZP_4-jkrjQRcA2R1hYFVh7s7EPHIrLdzF0da2J-rVOeswgL26PPGWTNll6n6mBQ-WVU7wS7pJP2rC_70mo9P8jXYcay4AMvYoYlthifxt8feSAhcOfazR6TuzhxDRl1hJtOyQXS3bVhfBV7c45kmC5Y98o6_6MmDHPwEV4sTYgeHySBxdNR7vbn2hmuBGh5Z0am8_vKpl4jSGHcS6LCBZqP86R-m8mx-yYEL70f3xPa2_y0AlKNb-cdwIsN6Yud59tiZHd1dGSg9qcUjaF4ttpYcNVO2P7BxFXgr2NYzEaVG19KlEKfDe5Mmj-bPU2nKCH6osibW3L6n30Q8zdRkiuhB2FBwgtBrhigee7c2Zvqidp-HUeuKZlPZjbegVOBSOlJqZ1TLBDhZr._riHxeCe4GkLAaS9&me=https%3A%2F%2Fsimon-indieauth.vercel.app%2F&state=eyJhIjoiaHR0cHM6Ly9pbmRpZWF1dGguY29tL2F1dGgifQ.i88YqkPoMc3yX2sBxKKMANAnNW4 

Full traceback:
```
Traceback (most recent call last):
File "/var/task/datasette/app.py", line 1033, in route_path
  response = await view(request, send)
File "/var/task/datasette/app.py", line 1210, in async_view_fn
  datasette=datasette,
File "/var/task/datasette/utils/__init__.py", line 915, in async_call_with_supported_arguments
  return await fn(*call_with)
File "/var/task/datasette_indieauth/__init__.py", line 130, in indieauth_done
  info = response.json()
File "/var/task/httpx/_models.py", line 1113, in json
  return jsonlib.loads(self.content.decode(encoding), **kwargs)
File "/var/lang/lib/python3.6/json/__init__.py", line 354, in loads
  return _default_decoder.decode(s)
File "/var/lang/lib/python3.6/json/decoder.py", line 339, in decode
  obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/var/lang/lib/python3.6/json/decoder.py", line 357, in raw_decode
  raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by simonw** [comment]
This happened when attempting to sign in using rel=me auth via indieauth.com BUT with the following HTML:
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Simon</title>
<link rel="authorization_endpoint" href="https://indieauth.com/auth"/>
</head>
<body>
<h1>Hello there</h1>
<li><a rel="me" class="u-url url" href="https://github.com/simonw" title="open source on Github"><img src="images/github-16x16.png" alt=""/> Github</a></li>
```

**Comment by simonw** [comment]
Here's the problem: I got back `me=https%3A%2F%2Fsimon-indieauth.vercel.app%2F&scope` when I was expecting JSON.

https://github.com/simonw/datasette-indieauth/blob/3fc5d4b7510f027c4d4f2c7cec0d7dae545f20af/datasette_indieauth/__init__.py#L129-L137

I could check the content-type header, but I'm tempted to instead check for a leading and trailing `{` `}`.
